version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - add_ssh_keys
      - run:
          name: Keyscan Github (HACK)
          command: ssh-keyscan -H server.actus.cl >> ~/.ssh/known_hosts
      - run:
          name: Deploy Over SSH
          command: |
            ssh-keyscan server.actus.cl >> ~/.ssh/known_hosts # Add live server IP to known hosts.
            ssh actus@server.actus.cl "cd public_sub/erp/"
            ssh actus@server.actus.cl "git fetch --all"
            ssh actus@server.actus.cl "git reset --hard origin/master"
            ssh actus@server.actus.cl "git pull origin master"
