version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh-keyscan server.actus.cl >> ~/.ssh/known_hosts # Add live server IP to known hosts.
            ssh actus@server.actus.cl "mkdir hola"
